### ISSUE TITLE
recent Listitem broken?

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#10]
Hi willforde,

Maybe I'm wrong, but the `Listitem.recent` seems to do something strange with callback arguments.

In the `next_page` function we have:

```python
[...]
item.art.global_thumb("next.png")
item.set_callback(route.callback, *args, **kwargs)
return item
```

But in the `recent` function we have:

```python
[...]
item.art.global_thumb("recent.png")
item.set_callback(callback, args, **kwargs)
return item
```

Notice the `item.set_callback` line. Is the "*" missing or I'm wrong?

Thank you!

Cc: @wwark

**Comment by willforde** [comment]
Your right! How did that one get passed me. Fixed now anyway.
Thanks.

**Comment by sy6sy2** [comment]
You're welcome!
