### ISSUE TITLE
Listitem.youtube() doesn't show "Not listed" youtube videos

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#13]
Hi Willforde,

I don't know if it's an issue but the `Listitem.youtube()` function works well only for "Listed youtube videos".

For example, if I call `Listitem.youtube('PLCnUnV3yCIYt_cgn_1UIU1w2YQ_TfFa6L')` I only have 5 videos on Kodi but if you go to https://www.youtube.com/playlist?list=PLCnUnV3yCIYt_cgn_1UIU1w2YQ_TfFa6L there is a lot of videos but most of them are "not listed".

Do you know if we can do something to fix that?

Thank you for your help!

cc @wwark

**Comment by willforde** [comment]
Ya, simple fix. It was ignoring 'unlisted' videos.

**Comment by sy6sy2** [comment]
Ah, yes I see now the `Skipping non plublic video` log message.
Are you going to allow unlisted videos in a release?

**Comment by willforde** [comment]
See: 0f22345
That code was there to skip private and restricted videos, I forgot about unlisted ones.
Let me know when you're finished work on your add-on and I will submit the update to Kodi then.
Thanks.

**Comment by sy6sy2** [comment]
Thanks to you ! :D

**Comment by wwark** [comment]
Thank you Willforde !

**Comment by sy6sy2** [comment]
Hi Willforde,

It seems that we are almost ready to release our add-on version that use your framework.

We forgot about that but we noticed that the "Search" history is common whatever the "Search" item triggered in the addon.
For exemple, in our case we have multiple TV channels, so multiple Search buttons. Do you provide to modify CodeQuick in order to distinct search history for each different search button (I think about a hash of the Kodi URL route used as a history id in order to district the different Search items?).

Thank you again!

**Comment by willforde** [comment]
That's something that I never thought of. I will look into it and get back to you.

**Comment by willforde** [comment]
I finished the code for restricting search items. But I haven't been able to fully test it yet, but it should be working.

**Comment by sy6sy2** [comment]
Oh thank you very munch for your work!

**Comment by willforde** [comment]
I'm ready to submit things to the Kodi repository. Just checking in in case there is one last thing that might need changing.

I also changed how I do sort methods so to prioritize the order of the manually set sort methods.

**Comment by wwark** [comment]
Thanks a lot @willforde I will test the last commit this evening.

**Comment by wwark** [comment]
All seems ok on my side. Thanks a lot. @SylvainCecchetto it is ok for you  ?

**Comment by sy6sy2** [comment]
Hi all,
Sorry for the delay, I’m currently on vacations but it seems ok for me too!

Thank you ;)

**Comment by willforde** [comment]
OK. I will submit the add-on to the Kodi repo. Hopefully it won't take as long to get accepted this time.
