### ISSUE TITLE
A way to quit silently from @Resolver.register function

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#15]
From a @Route.register function we can `return False` in order to quit silently without raising a RuntimeError, but from a @Resolver.register function, even if we return False CodeQuick raise an exception.

Is there a way to exit from a @Resolver.register function explicitly without raising an error like in a @Route.register function with a `return False`?

Thank you!

cc @wwark

**Comment by willforde** [comment]
You can now silently quick from a resolver callback.

**Comment by sy6sy2** [comment]
Thank you!

**Comment by willforde** [comment]
One thing to note is that from time to time Kodi will report that 'Playback failed'.
There is nothing that can be done about that.
