### ISSUE TITLE
Marking an item as watched doesn't do anything

### ISSUE THREAD

**Issue by wwark** [willforde/script.module.codequick#19]
Hi @willforde 
I hope you are well.

If you play a video or mark as watched a video, the video still remain to status not watched.
I tried with settings mediatype or not.
It is a misconfiguration or an issue on Kodi or on codequick ?
Thanks again for your help !

@SylvainCecchetto

**Comment by willforde** [comment]
I don't do anything with Watched flags. That should be all handled by Kodi.
I will look into it and see if I can find out why it's not working.

**Comment by willforde** [comment]
I just tested it now and for me, Watched flags work on all my add-on's and your Catch-up TV add-on.
Tested on Kodi v17.6 on Arch Linux.

**Comment by wwark** [comment]
Thank you for your tests so it means issue with Kodi 18 beta 5.
I will test on Kodi 17.6 also.

**Comment by willforde** [comment]
I tested the watched flags on different add-on's on Kodi v18 and some work but others don't. The youtube add-on was one that did not work.

**Comment by wwark** [comment]
Do you think it maybe fix with that https://github.com/xbmc/xbmc/pull/14810 ?
I will try on libreelec this evening because the last nightly include this fix.

**Comment by wwark** [comment]
I have test the last nightly the issue remain.
I will file a Jira ticket to understand this behavior

**Comment by willforde** [comment]
Same for me, not working. But it is working for the youtube add-on now.
I might be doing something that is conflicting and did some testing. I found that watched/unwatched worked when a Listitem is linking directly to a video, instead of redirecting back to the add-on to be resolved.

**Comment by willforde** [comment]
Found it. Kodi v18 don't like it when you use the path component of the add-on url, witch I was using for the route path. Now wether this is a bug with kodi or something that I should never have been doing in the first place, I don't know.

**Comment by wwark** [comment]
Thank you !
What is the impact to change to have listitem directly link to the video in codequick?
Maybe it is better you to ask Kodi Team about that. What do you think?

**Comment by willforde** [comment]
A simple fix in the end, just needed to add a trailing `/`.

**Comment by wwark** [comment]
Thank you ! I will test the last version of codequick :)
Have nice Sunday.
Wwark

**Comment by willforde** [comment]
The fix is now available in the latest release in the Kodi repo.
