### ISSUE TITLE
item.info season/episode shows as "available" totals

### ISSUE THREAD

**Issue by Forage** [willforde/script.module.codequick#21]
When setting

```
item.info["season"] = 1
item.info["episode"] = 2
```

This info is shown in the details of a specific video as "Available: 1 seasons (2 episodes)", though I don't think these elements should be treated as the totals, no?
It should count and shown as being the "season 1, episode 2" of that specific video, though I do not see this anywhere.

**Comment by willforde** [comment]
That is because you have not set the mediatype. 
```
item.info["mediatype"] = "episode"
```
[See more](https://codedocs.xyz/xbmc/xbmc/group__python__xbmcgui__listitem.html#ga0b71166869bda87ad744942888fb5f14)
