### ISSUE TITLE
[enhancement] A way to disable "Sets fanart to add-on fanart image if not set" feature

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#24]
Hi willforde,

CodeQuick has the features:

* Sets "thumbnail" to add-on icon image if not set
* Sets "fanart" to add-on fanart image if not set
* Sets "icon" to "DefaultFolder.png" or "DefaultVideo.png’ if not set
* Sets "plot" to the listitem title if not set
* [...]

Are you able to modify slightly you framework in order to force CodeQuick to not set an element to the plugin one if the element in not set?

Something like:

```python
item = Listitem()

# I do not want to have my addon icon here
# Just do not set "thumb" for this item
item.art["thumb"] = "disable"
```

Here, the "magic" keyword `disable` act as a "kill switch".

Thank you very munch!

@wwark: In the case of M6 Live TV from M3U, with this modification we would be able to have in the "media information" (keyboard "i" key) the logo from the M3U/XMLTV file instead of the Catch Up TV & More logo.

**Comment by willforde** [comment]
Yeah I can make changes to allow for that, something like `item.art["thumb"] = None` or `del item.art["thumb"]`

**Comment by sy6sy2** [comment]
Yes the `item.art["thumb"] = None` should be perfect! Thank you!

**Comment by willforde** [comment]
Done. Feel free to let me know if you have any more suggestions.

Thanks.

**Comment by willforde** [comment]
After doing some testing, I had to change it to accept an empty string in order to disable the automatic setting. 
``item.art["thumb"] = ""``

**Comment by sy6sy2** [comment]
Do you know what is the key to modify this one?
We are in a Live TV here.

<img width="1208" alt="Capture d’écran 2019-04-06 à 08 40 34" src="https://user-images.githubusercontent.com/11562279/55665953-dde1dd00-5847-11e9-806b-f898f6841ffe.png">


Thank you!

**Comment by willforde** [comment]
I'm not sure about that one. I can't test it as I have not seen that issue on my side.

**Comment by sy6sy2** [comment]
No problem, we will try to find the correct key for this one.
