### ISSUE TITLE
[question] Use a callback URL instead of a callback function

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#25]
Hi willforde,

Do you know if, for a given Listitem, I can set a callback URL instead of a registered callback function?

Something like that:

```python
@Route.register
def foo(plugin):
    item = Listitem()
    item.label = 'Test'
    item.set_callback(
        'plugin://plugin.video.example/?action=listing&category=Animals'
    )
    yield item

    item2 = Listitem()
    item2.label = 'Test 2'
    item2.set_callback(
        an_existing_callback_function
    )
    yield item2
```

item and item2 are both no playable item but folder.

Thank you for your help!

**Comment by willforde** [comment]
Done. You can now set a `is_folder` parameter in set_callback.
Or you can set `item.is_folder = True`, whichever works for you.

Will let you know when I have submitted the change to kodi.
Thanks.

**Comment by sy6sy2** [comment]
You rock! Thank you for both improvements!

**Comment by SylvainCecchetto** [comment]
Maybe I'm wrong, but the method `Listitem. from_dict` needs to be updated to take in account the new `is_folder` params?

**Comment by sy6sy2** [comment]
~~It seems that the`from_dict` function does not take in account the `is_folder` param.~~

~~Even if I have `item_dict['params']['is_folder'] = True`, I have to manually do a `item.is_folder = True` after a `item = Listitem.from_dict(**item_dict)`.~~

Edit: It seems that is not an issue from `from_dict`;
If I try this:

```python
item = Listitem()
item.params['id'] = "Foo"
item.set_callback("plugin://plugin.video.catchuptvandmore/main/generic_menu/")
yield item
```

Then I get:

```
Dispatching to route: '/main/generic_menu/'
Callback parameters: '{}'
```

My parameter `id` is lost :-/

But if I do:

```python
item = Listitem()
item.params['id] = "Foo"
item.set_callback(generic_menu)
yield item
```

Then everything is ok.

Edit2: I understand by looking your code, in the first case you assume that the url is complete (with parameters) so you don't call `build_path`.
So I have to build the complete path on my side ;-)

**Comment by willforde** [comment]
I get you now. I thought you were on about calling another add-on, not a callback within your add-on.
What you need so is a function that can convert a callback path to a callback object.
I'm already doing something like that myself internally, but have not exposed a way for the developer to do it.

Maybe I can change it so if you pass in a callback path, it will automatically convert it to a callback function if one exists.

``item.set_callback("/main/generic_menu/")``

**Comment by sy6sy2** [comment]
Yes it is what I want to do. Sorry for the lack of details.

Currently I have it working with this:

```python
def build_kodi_url(route_path, raw_params):
    query = '?' + urlencode(raw_params) if raw_params else ''
    url = route_path + query
    # print('Built URL: ' + url)
    return url

@Route.register
def favourites(plugin, **kwargs):
    item = Listitem.from_dict(**item_dict)
    url = build_kodi_url(item_dict['callback'], item.params)
    item.is_folder = item.params['is_folder']
    item.set_callback(url)
    return item
```

I previously obtain `item['callback']` with `xbmc.getInfoLabel('ListItem.Path')`.

Don't know if it's a robust solution :-/

The final goal is to implement a Favorites folder.
The user can add any item (playable or folder) to its favorites with a context menu button.
Then we save the favorites in a PersistentDict.

When the user enter in the Favourites folder with iterate over each item_dict in the PersistentDict.

I will attach you the complete code of this feature if you want to take a look

Edit: A little Python file with the minimum number of function to understand : 
[example.py.txt](https://github.com/willforde/script.module.codequick/files/3050570/example.py.txt)

**Comment by willforde** [comment]
I have added that feature now. Both features are useful anyway.
Good luck with the "Favorites folder", hope if works out the way you want.

**Comment by sy6sy2** [comment]
Thank you very munch, I will try it!

**Comment by willforde** [comment]
Also may I suggest you use Script callbacks,  instead of returning False when using Route.

**Comment by sy6sy2** [comment]
Just tested your changes, seems to works well 👍 

We return False because we found this info in the doc: `False: This will cause the “plugin call” to quit silently, without raising a RuntimeError.`.

What's the correct value to return when we do not want to "move"?

**Comment by willforde** [comment]
You return False on a Route if that callback normally returns content, but If a user cancels a dialog box, then you can return False to stop it from raising an error. 

But if your callback will never return content. Then using a Script callback is desired, as it's not expecting any content. it just runs a script and returns.

It don't really matter anyway as things will still work fine witch ever way you do it.

**Comment by willforde** [comment]
I have submitted the update to the Kodi repo and it should be available soon. So sorry for the delay.

https://github.com/xbmc/repo-scripts/pull/1050
