### ISSUE TITLE
return a @Route.register function from another @Route.register function

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#26]
Hi willford,

We have a little issue with a feature we added in our addon.
Let's take this little example, assume the addon menu structure is this one:

* Live TV
    * France
        * TF1
            * All programs
            * Recent
    * Belgium
         * RTL-TVI
            * All programs
            * Recent
        * La Une
            * All programs
            * Recent
* Website
    * Allociné
    * Tete à claques

Now the user opens the addon, then he chooses `Live TV`.
Now the current menu has for items `France` and `Belgium`.
Now the user chooses `France`.
With the normal behavior, the menu that opens contain the only item `TF1`.
But as you can see, `France` has only one channel (`TF1`).
So the new feature detects (during the construction of the `France` menu) that the only item is `TF1`, so instead of create an item for `TF1` and return this item we directly `return` the callback function of `TF1` in order to directly bring the user in the `TF1` menu.

First question: Do you think is "correct" to return a callback function directly from another callback function?

So, actually this features works, BUT, when the user reaches the `TF1` menu (with `All programs` and `Recent ` items) the path that you see at the left top screen is wrong and show `France` instead of `TF1`.
I think that this information is set by `xbmcplugin.setPluginCategory()` in your framework.
Do you know if this issue can be fixed?
Maybe your answer at the first question will automatically resolve this issue ;-)

Thank you for your help! We really appreciate your reactivity and the changes you make in CodeQuick for us.

poke @wwark

**Comment by willforde** [comment]
With the way that things work at the moment, you could check if there is only 1 listitem and then just call that callback function yourself. You just have to pass in the plugin object as the first argument and whatever else you need and just return the results from that function.

In relation to setPluginCategory you can manually set it yourself with `plugin.category = "TF1"`.
It should be setting it to "TF1" itself, not sure why it's not. 
I will need to play around with your code to see why it's not working the way it should.
Where about can I find the specific code related to that callback.

**Comment by sy6sy2** [comment]
> With the way that things work at the moment, you could check if there is only 1 listitem and then just call that callback function yourself. You just have to pass in the plugin object as the first argument and whatever else you need and just return the results from that function.

This exactly what we do ;-)

> In relation to setPluginCategory you can manually set it yourself with plugin.category = "TF1".
It should be setting it to "TF1" itself, not sure why it's not.
I will need to play around with your code to see why it's not working the way it should.
Where about can I find the specific code related to that callback.

I will try to prepare a minimal code for you to highlight this. Thank you!

**Comment by willforde** [comment]
O, Sorry I didn't fully read the issue right. I'm not that good at reading.
I understand what you are asking now. Setting ``plugin.category = "TF1"`` will fix the issue with France showing up instead of "TF1". There is no other way around that when you directly call a sub callback.

While having CodeQuick skip showing just one item and instead redirecting to it should be possible. I don't think that would be a good thing to do by default, as it would be confusing to other developers.
But maybe there can be a veriable that you can set to enable that feature if required.
Something like ``plugin.redirect_single_item = True``.

Would that work for what you want to do.

**Comment by sy6sy2** [comment]
I will try the `plugin.category = "TF1"` ;-).

Yes the `plugin.redirect_single_item = True` would be very nice! But you are right, this option should be set explicitly and not enable by default.

**Comment by willforde** [comment]
I have changed things a bit to allow for the redirect to work. I didn't get the chance to fully test it yet, but it should work find as I didn't really change much.

Let me know if you experience any problems.

**Comment by sy6sy2** [comment]
Just tried the `plugin.redirect_single_item = True`, it works perfectly fine and the category is the good one without using `plugin.category`! You rock! Thank you!
