### ISSUE TITLE
Raise a custom exception when run_callback failed

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#27]
Hi willford,

Is it possible to raise a custom defined exception at the end of https://github.com/willforde/script.module.codequick/blob/1fc411ec8b7caf6ed896037835e0d00352944600/script.module.codequick/lib/codequick/support.py#L287-L299

That way we could wrap `run()` with a try/catch block and perform some post treatment on our side when something goes wrong.

Thank you very munch

poke @wwark

**Comment by willforde** [comment]
Hi. That is actually a good idea.

I was thinking how best to implement it, and have come up with 2 options.
* Add an option to disable the internal exception handling so to allow for custom error handling using try/except.
* Set it so the run function returns the Exception that was raised so you can do some extra processing on the error. Returns None if no error was raised. The Error message could also be suppressed by passing in `suppress_error_msg=True`.

I like the second option more. What do you think.

**Comment by willforde** [comment]
After a bit of thinking I have decided to do a bit of both options.

The run function will now always return the Exception that was raised if an error occurred. Otherwise it will return ``None``.
You can now also disable the internal exception handling by passing ``process_errors=False`` to the run function. In-case you want more fine control over the error handling.

I have also changed the register_delayed feature so you can set a delayed function to run only if no errors occurred, or only if an error occurred, or regardless of wether there was errors or not.

53c50576e2a7b6855ca54d8d524671e017e0419f

**Comment by sy6sy2** [comment]
Sounds good! Thank you!
I will try to achieve what we want concerning this improvement and I will let you know if it works as we expect.

**Comment by willforde** [comment]
I have changed the delayed function calls so you can now access the exception that was raised if there was an error. Just add an argument to the delayed function called "exception", and it will be set to the raised exception object.

**Comment by sy6sy2** [comment]
Thank you very munch, I will try to try this feature tonight if I have time

**Comment by sy6sy2** [comment]
This is the first time that is use the "delayed function" feature and I notice that there is no `@Script. register_delayed ` decorator and instead we need to manually call `Script.register_delayed(error_handler, function_type=1)` :-/

I would like to register my function `error_handler` EVERYTIME.
I tried to add this line before `run()` but as expected it won't works.
Is there a way to do this?

**Comment by willforde** [comment]
The register_delayed feature is more designed to run functions related to a specific callback, instead of always been called.

If you want code to run every time you call run, you would be better off to use the following example.
```
exception = run()
if isinstance(exception, CustomException):
    # Handle exception
    pass
```

Dose that work for what you are trying to do.

**Comment by sy6sy2** [comment]
Yes its perfect now that `run()` follow the exception!
Thank you very munch!
