### ISSUE TITLE
Support both Python 2 and 3 (pickle)

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#29]
Hi willforde,

We are currently porting our Addon to be compatible with both Python 2 and Python 3 (because of that: https://kodi.tv/article/attention-addon-developers-migration-python-3).
Master branch (and last nightly builds) of Kodi now used Python3 so we can easily test our addon.

It seems that codequick failed at some point during the pickle steps. Can you have a look if you have time?

This is what I get with a Python3 Kodi build:

```python
File "/Users/sylvain/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/listing.py", line 518, in script
    command = "XBMC.RunPlugin(%s)" % build_path(callback, args, kwargs)
File "/Users/sylvain/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/support.py", line 375, in build_path
    pickled = binascii.hexlify(pickle.dumps(query, protocol=pickle.HIGHEST_PROTOCOL))
       TypeError: can't pickle xbmcgui.ListItem objects
``` 

Thank you!

cc @wwark

**Comment by willforde** [comment]
I'm not really sure whats going on there. I can have a look at it in a few days.

**Comment by sy6sy2** [comment]
Hello Willforde, it seems that this issue was caused by an error in our code, my fault :-/
Sorry for inconvenience.
