### ISSUE TITLE
is it possible to use default 'audio switcher menu' in kodi addons?

### ISSUE THREAD

**Issue by byaka** [willforde/script.module.codequick#3]
Site that im scrapping allows watching episodes with different audio tracks. Technically its different video files. But how can i give user ability to switch them? Ideally i want to fill and 'hook' default audio-switcher menu. But googling shows me nothing

**Comment by willforde** [comment]
I'm not sure that something like that is possible. Kodi has no API to access that.
The only way that I can see that working is if the video file has all the audio tracks merged into the video stream on the fly. Good luck with that one.

**Comment by byaka** [comment]
crap. ty

one more stupid question: adding items to left-sidebar also not possible?

**Comment by willforde** [comment]
What do you mean by left-sidebar.

**Comment by byaka** [comment]
https://iwf1.com/wordpress/wp-content/uploads/2015/11/Kodi-check-for-updates.jpg

**Comment by willforde** [comment]
I don't know about that one.

**Comment by Forage** [comment]
I suppose I just ran into the same issue.
Normally when you let Kodi open a m3u8 file directly with multiple audio streams it will automatically provide you a list of audio streams to choose from. Providing the exact same file as URL through codequick does not.
Is this an add-on or Kodi limitation?
