### ISSUE TITLE
Improve Listitem.from_dict() method

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#30]
Hi willforde!

A Listitem has those attributes:
* callback
* label
* subtitles
* info
* art
* stream
* context
* property
* params

But the `from_dict` method takes only:
* callback
* label
* info
* art
* stream
* context
* properties
* params

Is there a reason why `from_dict` can not take a subtitle list?

Thank you ;)

**Comment by willforde** [comment]
No reason what so ever. I added subtitles later on after I released codequick, and just forgot about adding it to from_dict.

**Comment by sy6sy2** [comment]
Thank you!
