### ISSUE TITLE
ImportError: Failed to import _strptime because the import lockis held by another thread

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#33]
Hi @willforde,

We have some users (at least two ATM) that encounter this error:

```
2019-12-13 22:08:28.814 T:6813   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-12-13 22:08:29.374 T:17211  NOTICE: [Catch-up-TV-&-More] [cq_utils.import_needed_module] Import module resources.lib.channels.fr.mytf1 on the fly
2019-12-13 22:08:29.550 T:17211   FATAL: [Catch-up-TV-&-More.support] Failed to import _strptime because the import lockis held by another thread.
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 295, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 95, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 34, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1.py", line 204, in list_videos
                                                item.info.date(video_datas['date'].split('T')[0], '%Y-%m-%d')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/listing.py", line 300, in date
                                                converted_date = strptime(ensure_native_str(date), date_format)
                                            ImportError: Failed to import _strptime because the import lockis held by another thread.
2019-12-13 22:08:29.550 T:17211 WARNING: ###### debug ######
2019-12-13 22:08:29.551 T:17211 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/fr/mytf1/list_videos/'
2019-12-13 22:08:29.551 T:17211 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{'video_type_value': u'replay', u'is_playable': False, 'program_slug': u'burger-quiz', u'is_folder': True, 'offset': u'0', 'item_id': u'tmc'}'
2019-12-13 22:08:29.551 T:17211 WARNING: [urlquick] Requesting resource: https://www.tf1.fr/graphql/web?variables=%7B%22programSlug%22%3A%22burger-quiz%22%2C%22offset%22%3A0%2C%22limit%22%3A20%2C%22sort%22%3A%7B%22type%22%3A%22DATE%22%2C%22order%22%3A%22DESC%22%7D%2C%22types%22%3A%5B%22replay%22%5D%7D&id=6708f510f2af7e75114ab3c4378142b2ce25cd636ff5a1ae11f47ce7ad9c4a91
2019-12-13 22:08:29.551 T:17211 WARNING: [urlquick] Request headers: {u'Accept-language': u'en-gb,en-us,en', u'Accept-Encoding': u'gzip, deflate', u'Connection': u'keep-alive', u'Accept': u'*/*', u'User-Agent': u'<function get_random_ua at 0x235d86aba0>', u'Host': u'www.tf1.fr', u'referer': u'https://www.tf1.fr/programmes-tv', u'content-type': u'application/json'}
2019-12-13 22:08:29.551 T:17211 WARNING: [urlquick] Cache is fresh, returning cached response
```

You will find another one here: https://paste.kodi.tv/oxexaxorit

I spoke with a Kodi team member about it and it seems that's an old well know Python issue (race condition with threads, I know that you are not using thread in CodeQuick but maybe Kodi use Thread to launch Python addons?).

The Kodi team member says me that we can use a fix from this thread: https://forum.kodi.tv/showthread.php?tid=112916

I also find this thread: https://www.raspberrypi.org/forums/viewtopic.php?t=166912

Can you have a look?

Also, do you plan to release a new version of Codequick with the latest commit?

Thank you ;-)

**Comment by willforde** [comment]
Sorry for the lack of support recently on this project. I have been very busy with a new SAAS startup, but thankfully it's just about finished. Just have one thing left to sort out and I can take a break from it for a while and focus on other projects again. 
As soon as I'm able, about a week from now, I will look into the current issues and finally push an update to Kodi.

P.S. If you have any other issues that you would like me to have a look at, Please let me know.

**Comment by sy6sy2** [comment]
No problem willforde, take your time, real life comes first ;-)

ATM I have no other issue in my mind, maybe @wwark?

Edit: I think of one thing, this is not an issue but a new "feature", concerning https://scriptmodulecodequick.readthedocs.io/en/latest/api/listitem.html#codequick.listing.Listitem.set_callback we can use the *The path to a callback function. i.e. “/main/menu/”* as a string, but this function need to be already registered. Do you think that you can modify your framework in order to be able to pass the path of a callback function event if this function is not yes registered?
Because in our case we have a lot of modules, so in the entry point Python file, and just before the `run()` call, we parse `sys.argv[0]`in order to load on the fly with `importlib.import_module()` the module found in sys.argv[0].
I am not sure to be very clear, I can explain with more details if needed ;-)

**Comment by willforde** [comment]
I will have a look at the import problem now.

In relation to the dynamic importing based on the path, that would be a very nice feature to have. I would like to have it myself. I attempted to add that feature before but I couldn't find a solution, but I have a lot more experience now so maybe I might be able to get that feature working.

**Comment by willforde** [comment]
I have made a very small change to import ' _strptime'. Hopefully this will fix the issue. 
If you are able to test the fix that would be great.

**Comment by sy6sy2** [comment]
Thank you for the `strptime` fix, I hope it will fix the issue. I can not test myself because the issue was reported by an user of our add-on and the issue seems to happen randomly...

Concerning the dynamic import, we already do it in our add-on (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/tree/dev).
You can find below the minimal code to implement it:

```python

def get_module_in_query(query_string):
    """Get module from Kodi query (sys.argv[2]) in CodeQuick special case (Search feature)
    Args:
        query_string (str): Query string passed to the addon (e.g. ?foo=bar&baz=quux)
    Returns:
        str: Module to load after the Search window (e.g. resources.lib.channels.fr.francetv)
    """

    module = ''
    params = get_params_in_query(query_string)
    # '_route': u'/resources/lib/channels/fr/francetv/list_videos_search/'
    if '_route' in params:
        base_url = params['_route']
        # Remove last '/'
        if base_url[-1] == '/':
            base_url = base_url[:-1]

        # Remove first '/'
        if base_url[0] == '/':
            base_url = base_url[1:]

        base_url_l = base_url.split('/')
        module_l = []
        for word in base_url_l:
            module_l.append(word)

        module_l.pop()  # Pop the function name (e.g. list_videos_search)
        module = '.'.join(module_l)
        # Returned module: resources.lib.channels.fr.francetv

    return module


def get_module_in_url(base_url):
    """Get module from Kodi base URL (sys.argv[0])
    Args:
        base_url (str): Base URL string passed to the addon (e.g. plugin://plugin.video.catchuptvandmore/resources/lib/websites/culturepub/list_shows)
    Returns:
        str: Module found in the base URL (e.g. resources.lib.websites.culturepub)
    """

    if 'resources' not in base_url:
        return 'resources.lib.main'

    # Remove last '/'
    if base_url[-1] == '/':
        base_url = base_url[:-1]

    # Remove plugin_id
    base_url = base_url.replace('plugin://plugin.video.catchuptvandmore/', '')

    base_url_l = base_url.split('/')
    module_l = []
    for word in base_url_l:
        module_l.append(word)

    module_l.pop()  # Pop the function name (e.g. list_shows)
    module = '.'.join(module_l)

    return module


def import_needed_module():
    """Import needed module according to the Kodi base URL and query string
    """

    modules_to_import = [get_module_in_url(sys.argv[0])]
    if 'codequick/search' in sys.argv[0]:
        modules_to_import.append(get_module_in_query(sys.argv[2]))
    for module_to_import in modules_to_import:
        if module_to_import == '':
            # No additionnal module to load
            continue

        # Need to load additional module
        try:
            Script.log('[import_needed_module] Import module {} on the fly'.format(module_to_import), lvl=Script.INFO)
            importlib.import_module(module_to_import)
        except Exception:
            Script.log('[import_needed_module] Failed to import module {} on the fly'.format(module_to_import), lvl=Script.WARNING)

def main():
    """Entry point function executed by Kodi for each menu of the addon
    """

    """
    Before calling run() function of
    codequick, we need to check if there
    is any module to load on the fly
    """
    import_needed_module()

    """
    Then we let CodeQuick check for
    functions to register and call
    the correct function according to
    the Kodi URL
    """
    run()


if __name__ == "__main__":
    main()
```

**Comment by willforde** [comment]
I have added the support to dynamically load the module where a callback is located, if that callback was not already registered. The only limitation is that if the module that contains the `root` callback is not located at `resources.lib.main`, then it will need to be manually imported.

This feature allowed me to not have to import the Youtube module every time the add-on loaded anymore. This should speed things up a small bit.

**Comment by willforde** [comment]
I can easily add code to auto import `resource.lib.main` but I'm not sure if I should. What do you think?

**Comment by sy6sy2** [comment]
Thank you very munch for this feature!
I will try it this week an I will let you know how it work with our plugin 😉

**Comment by sy6sy2** [comment]
Hi willforde,

Sorry for the delay, I just tried your last feature (_dynamically load the module where a callback is located_) but I have an issue with this case:

1. I am in `plugin.video.catchuptvandmore/resources/lib/main.py` an I build a Kodi directory with only one item
2. For this item I want Kodi to open the `list_categories` function from the `plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1.py` file. So I use the `item.set_callback('/resources/lib/channels/fr/mytf1/list_categories/')` line in `main.py`.

But when I select this item I get a `ERROR: CGUIMediaWindow::GetDirectory(/resources/lib/channels/fr/mytf1/list_categories/) failed` error.

Do you know why?

Also, I do not import `plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1.py` in `main.py` (because I hope CodeQuick will dynamically load `plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1.py` on the fly after the item selection).

Thank you!

**Comment by willforde** [comment]
I think i know the issue and should be an easy fix.

**Comment by sy6sy2** [comment]
Hi willforde, I hope you are ok!
Did you have time to look at this issue?
Thank you!
