### ISSUE TITLE
Submit next version of CodeQuick on both Krypton/Leia AND Matrix

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#35]
Hi willforde,

I don't know if you saw the news, but all add-ons and scripts already available on Krypton or Leia official Kodi repositories WILL NOT BE available for end users on Kodi Matrix, even if the plugin/script is compatible with both Python 2 and Python 3.

So, for us, and also for you, it is mandatory to open a new submission of our plugin/script in the Matrix repo with `<import addon="xbmc.python" version="3.0.0"/>` in our `addon.xml` file.

You can find the long story [here](https://forum.kodi.tv/showthread.php?tid=351745) and [here](https://github.com/xbmc/xbmc/issues/17326).

This issue is just to be sure that you are aware of this change, feel free to close it when you want 😉 

Thank you for your work!

**Comment by willforde** [comment]
They are changing things up, great. Good bye python2. I like the way they are doing it now. Clean slate. 

Thanks for the heads up.

**Comment by willforde** [comment]
Just noticed your work on making "youtube.dl" python 3 compatible, great job. I was wondering if that was ever going to get updated.

**Comment by sy6sy2** [comment]
Yes but ruuk seems to be absent since a long time. I will discuss with the Kodi team to know if I can submit a new update of Youtube-DL myself on the Kodi repo(s).
