### ISSUE TITLE
Future of the framework

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#38]
Hi @willforde,

We hope all is well for you.
We haven't seen you for a while on your Github so we take the liberty of asking you if you wish to keep maintaining this framework in the future?

Of course we all have a life next to Kodi and maybe you just lack time? If this is the case maybe do you prefer some help with pull request?

On another side, if you decide to not maintain this framework anymore, we will need doing otherwise for our add-on (fork your framework to update it, embedded you framework in our code, ...).

Thank you for your time and for your framework!

cc: @wwark

**Comment by willforde** [comment]
Yeah I'm still alive, thanks for asking. Sorry for not being very active as of late. I just have been feeling a bit burnt out recently. couldn't get motivated. I hope things are good on your side.

I do want to keep working on the framework though. I have had plans to improve it, like add support for caching listitems and rewrite the urlquick module to be a wrapper around requests, just with a custom caching adapter. While also cleaning up the code a bit. I also mostly finished creating a program to allow for running and testing Kodi addons without the need for Kodi, utilizing pytest.

So I would love to get back to all that and finish things. I just need to get motivated again.
I will try and get the current version released soon.

Of course pull requests are always welcome.

**Comment by sy6sy2** [comment]
It's good to hear that you are well! Thank you for your fast reply.

Wow your plans are fantastics! I look forward to trying all of this.
Concerning the _runnning and testing Kodi add-on without the need for kodi_ we currently have something that we in our CI --> https://github.com/Catch-up-TV-and-More/catchuptvandmore-test I'm sure that a lot of thing need to be improve but if you one to have a look 😉 

Thank you and see you very soon!

**Comment by sy6sy2** [comment]
Hi willforde,

Also, I don't know what is your current roadmap in term of date concerning the new features you want to create. But do you think that is it possible for you to release a new version (0.9.11) on Kodi repo based on your master branch? Since 0.9.10 you added some feature and bug fix that we would like to benefit in our add-on for our users.
Unfortunately, these bug fix and features are only available on your master branch on "normal" Kodi users cannot benefit of it.

If it's not possible there is no problem, we will wait 😉 

Thank you!

**Comment by willforde** [comment]
I was planning on doing just that. Release what I have now after a bit of testing then get my video addon's updated. After that I will work on the improvements then on a separate branch.

I was planning on getting back to work on this before the end of the week. And should have the new release out before the end of the weekend.

**Comment by sy6sy2** [comment]
You rock! Thank you very munch!

**Comment by willforde** [comment]
Just a quick update. I am having a few issues getting the callback path to work on other methods too, like the search and context items. So might take a few more days before it's ready.

EDIT: Never mind found a solution. Just need to update tests now.

**Comment by willforde** [comment]
Just submitted version 0.9.12 to the repo. Enjoy.

**Comment by sy6sy2** [comment]
Thank you very munch 🙏
