### ISSUE TITLE
[discussion] Persistent storage improvments (TTL, auto-flush etc.)

### ISSUE THREAD

**Issue by byaka** [willforde/script.module.codequick#4]

**Comment by willforde** [comment]
I have changed the storage objects to add support for TTL.
See ffea630

**Comment by byaka** [comment]
ty
if i not missed something, ttl expiration checking only on init. So if ttl lower than script's executing time - script will have expired data until restart. I think its not big problem, just need to be explained in doc.

**Comment by byaka** [comment]
also one stupid question - why flushing only manual? Just in my opinion 'by-default' persistent storage must have auto-save mode if script ended without exceptions. Your cool framework have alot things, that simplifing addon-developing but this one is... strange

**Comment by willforde** [comment]
I attempted to change when I do the expiration check, but I noticed that there was too high of a chance of a race condition. Data could expire in between checking existence of data and processing it.

I see you're point on the flushing. I have set it to flush whenever the object is closed.
Thanks. I'm always looking for ways to simplify things.

**Comment by byaka** [comment]
Thanks for mantaining this project!

I dont know enouth about Kodi's plugin architecture, so maybe thing that i'll say now just stupid. How about creating separated process, that allow comunicating by socket (*UDS where possible, where not - local TCP) and implements simple locking mechanism on it. So when some script want to CHANGE, CHECK, LOAD or DUMP persistent storage, it send LOCK and after all done, UNLOCK. Becouse this separated process dont do anything heavy, only store LOCKING status per storage - i'm sure it bring minimal overhead (especially over *UDS where possible). And you will have simple and dereminated locking mechanism on all platforms without potential problems with IPC.
What u thinking about this way?

**Comment by willforde** [comment]
Something like that already exists for Kodi. [https://kodi.wiki/view/Add-on:Common_plugin_cache](https://kodi.wiki/view/Add-on:Common_plugin_cache)
I looked into using it before, but there was a noticeable delay when importing the module, more than I was comfortable with.

**Comment by byaka** [comment]
hmm intersting, missed this lib.
