### ISSUE TITLE
Mark video item as watched bug with CQ 0.9.13

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#41]
Hi @willforde,

@wwark just notice an issue with our plugin.
When we watch a video until the end this video is not marked as watched anymore (the little tick icon next to the video item). Instead, the item keep its little square icon.

After some tests I notice that this issue is not present with CQ 0.9.12 but I have the issue with CQ 0.9.13 (with the same version of our addon).

Do you know what change can cause this issue?

If you need some test or log we are here 😉 

Thank you!

**Comment by willforde** [comment]
Dam. Totally forgot about the old Kodi bug. #19
Kodi really want's a trailing '/'

**Comment by sy6sy2** [comment]
Woh ; completely forgot this 2 years old issue too 😕

**Comment by sy6sy2** [comment]
Your fix works as expected! Thank you 😉

**Comment by wwark** [comment]
Thank you for the fix. Really appreciated.
