### ISSUE TITLE
Add your framework in the Official Kodi Wiki

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#42]
Hi @willforde,

I am not sure that a lot of people use your framework for Kodi Python addons (and they are wrong 😛).

There is a wiki page here with some framework https://kodi.wiki/view/Development_Tools#Frameworks, do you want to be added here? I can add you if you want?

**Comment by willforde** [comment]
Yeah. That would be great. Thanks.

**Comment by sy6sy2** [comment]
Done 😉 
You're welcome, feel free to ask if you want a change. Also you can create an account and modify the wiki page by yourself (IIRC the wiki can be edited by non Kodi team members).
