### ISSUE TITLE
Remove LOGNOTICE from python add-ons (Kodi 19)

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#43]
Hi @willforde, how are you?

Just a message to tell you that `xbmc.LOGNOTICE` was removed from Kodi 19 since this PR merge https://github.com/xbmc/xbmc/pull/18346.

Codequick use this constant so currently your framework does not work on Kodi 19 😉 

Thank you!

cc @wwark

**Comment by willforde** [comment]
O, Thanks. I will change that in a few days. Plus make the required changes for python 3.
Do you know if the youtube.dl addon was updated to support python 3 yet.

**Comment by sy6sy2** [comment]
YT-dl works great with Python 3 but unfortunately @ruuk has not yet submitted its addon to Matrix official repo.
But you can find a working Python 3 version here https://github.com/ruuk/script.module.youtube.dl/tree/master-kodi19

**Comment by willforde** [comment]
Hello. I'm back again. I have made all the changes that are required for v19. You can find it in the v19 branch.
I hope @ruuk submits the python 3 version soon, now that Kodi v19 is moving into beta.

I haven't tested any of the python 3 stuff on Kodi yet though.

**Comment by sy6sy2** [comment]
Hi willforde,
Glad to see that you are still on the spot 😉 
Thank you for this update!

Concerning YT-DL I know that ruuk did not submit it for Matrix yet. He also need to check the PR with some fixed and Matrix related changes like you did for CQ. 😕
I will try to ping him on Slack to ask him about the future of YT-DL.

Concerning our addon, it should also works on Matrix. We will try it with your v19 branch as soon as possible 😉
Do you plan to submit it on the repo soon?

**Comment by sy6sy2** [comment]
I did not perform an in-depth test but I can confirm that the v19 branch works on Kodi 19 alpha 3 with our addon for standard tasks like navigation and play video 👍 🙏
