### ISSUE TITLE
[urlquick 2] max_age is not working

### ISSUE THREAD

**Issue by iMro0t** [willforde/script.module.codequick#45]
In urlquick 2 from codequick module, `max_age=-1` is not working as expected. 
It's still returning cached response instead of ignoring the cache. 

https://github.com/willforde/script.module.codequick/blob/5caf50c6e9dd64e073f92feb3385186727b91645/script.module.codequick/lib/urlquick.py#L298-L300

I dig into and found that changing `CASE WHEN ? == -1 THEN 1` in line 299 to `CASE WHEN ? == -1 THEN 0` works as expected. 

Take a look at it. Thanks

**Comment by willforde** [comment]
Yeah. That's my bad. Urlquick was always treating `max_age=-1` as forcing it to always return the cached response. I messed up the documentation. That's a big oops, sorry. I still need to update the documentation for urlquick 2.
If you don't need the caching then you would be better off to use requests directly. Especially now that urlquick 2 is a wrapper for requests.
Sorry again for the confusion. I can't believe this never came up before.

**Comment by willforde** [comment]
I just looked again at the original code and notice that in one place I was treating -1 as force cache. But in another it never used the cache if it was less than 0. Shit. I will make the required change to make urlquick work like it's supposed to.

**Comment by willforde** [comment]
That's fixed now.

**Comment by iMro0t** [comment]
Thanks @willforde , that was quick :beers:
