### ISSUE TITLE
CodeQuick v1.x.x is broken on Krypton

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#46]
Hi @willforde,

Just tested Catch-up TV & More on Kodi 17-Krypton (my fault, I should have done it earlier) and it seems that the framework is broken on this version of Kodi.

With Codequick v0.9.14 everything is ok but with Codequick v1.0.2 when we open our plugin there is no ListItem.

```
16:30:04.377 T:123145373315072   DEBUG: [Catch-up-TV-&-More.support] Dispatching to route: 'root'
16:30:04.377 T:123145373315072   DEBUG: [Catch-up-TV-&-More.support] Callback parameters: '{}'
16:30:04.377 T:123145373315072   DEBUG: [Catch-up-TV-&-More.support] Attempting to import route: resources.lib.main
16:30:04.569 T:123145373315072   DEBUG: [Catch-up-TV-&-More.route] Listitem Cache: Miss
16:30:04.741 T:4597366208   DEBUG: ------ Window Init (DialogBusy.xml) ------
16:30:04.745 T:123145373315072   DEBUG: [Catch-up-TV-&-More.support] Route Execution Time: 176ms
16:30:04.745 T:123145373315072    INFO: CPythonInvoker(10, /Users/sylvain/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
16:30:04.753 T:123145375997952   DEBUG: Thread BackgroundLoader start, auto delete: false
16:30:04.759 T:4597366208   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
16:30:04.764 T:123145375997952   DEBUG: Thread BackgroundLoader 123145375997952 terminating
16:30:04.794 T:123145373315072    INFO: Python script stopped
16:30:04.794 T:123145373315072   DEBUG: Thread LanguageInvoker 0 terminating
16:30:05.255 T:4597366208   DEBUG: Keyboard: scancode: 0x00, sym: 0x0132, unicode: 0x0000, modifier: 0x0
```

<img width="1011" alt="Capture d’écran 2021-03-02 à 16 30 31" src="https://user-images.githubusercontent.com/11562279/109671682-961f7980-7b74-11eb-9d1c-23eae22c6620.png">

Thank you for the help.
cc @wwark

**Comment by willforde** [comment]
Shit. It's probably something small. Hopefully. I closed the pull requests to kodi.  I will look at the issue later.

**Comment by willforde** [comment]
That issue is fixed now. Might submit it tomorrow if no other issues arise.

**Comment by wwark** [comment]
Thanks a lot Wilforde !

**Comment by sy6sy2** [comment]
Thanks willforde for the fix. 
Just tested your master branch on Kodi 17.6/iOS/Catch-up TV and I did not notice any problem.
