### ISSUE TITLE
Questions about features

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#5]
Hi willforde,

I just discovered your framework and I have some questions before I jump in ;-)

We currently use the SimplePlugin (https://github.com/romanvm/script.module.simpleplugin) framework with our add-on (a Catch-up TV / Live TV plugin that use a lot of web scrapping methods and API calls).

The original creator of SimplePlugin no longer maintains the framework so we think about changing the framework.
First of all we constat that there is not many framework for Kodi add-ons, I only found yours and SimplePlugin ...

After a brief comparaison between SimplePlugin and CodeQuick I notice some differences.

With SimplePlugin we use this features:
* _GNU Gettext emulation for simplified addon GUI localization: you can use English source strings in your Python code instead of non-obvious numeric string codes._
* _Caching decorator that allows to cache function return data for a specified amount time, for example, to reduce the frequency of polling data from some website._

Do you know if we can do something similar with your framework? By reading the doc I don't notice something about that.

Thank you very munch and we hope that your framework will be a good candidate to replace SimplePlugin ;-)

**Comment by willforde** [comment]
Gettext emulation is a very good idea, will add that within the next few days.

For caching I created a module called urlquick, witch is a light-weight HTTP client with requests like interface featuring caching support. It defaults to a 4 hour cache but it can easily be changed.
I was also thinking of changing urlquick to just add caching support to requests itself, now that kodi(Leia) caches loaded modules which make the next call so much faster.

**Comment by sy6sy2** [comment]
Oh cool! Thank you for your answer about Gettext emulation.

Concerning the memory caching:
Yes I know about the caching support of URLQuick, but I was thinking about caching the ListItem list of a menu built from a parsed HTML by HTMLement. My real question is: 

Is it longer to do the sequence:
```
resp = urlquick.get(url)
root_elem = resp.parse(u"ul", attrs={"id": "category_listing"})
for elem in root_elem.iterfind("li"):
    a_tag = elem.find("a")
    item = Listitem()
    item.label = "%s (%s)" % (a_tag.text, elem.find("span").text)
    item.set_callback(video_list, cat=a_tag.get("href"))
    yield item
```
as many times as the user open this menu OR is it longer to save in a cache on the RAM the ListItem list the first time the menu is built, and use this cache each time the user opens this menu? I suspect the `root_elem = resp.parse(u"ul", attrs={"id": "category_listing"})` to be the "longer" task in this function and this is why I think about the caching, but maybe I'm wrong and this line is fast enough to not use a caching trick here.

By the way, is it possible with URLQuick to "get" an URL without storing the HTML file on the disk but just the content of it in a Python object, I think that it would be useful for small web pages that we only want to read one time? What do you think about that?

**Comment by willforde** [comment]
I tested the speed of HTMLement before and it takes on average 300ms. I just tested my addon's and the average loading time for everything was about 450ms, including imports. And a lot of that is down to Kodi, as I remember, Kodi was a lot faster at loading addon's before. There seams to be some kind of delay with kodi listitems. But with Kodi 18 the speed varied from 250ms to 700ms.

I did test listitem caching before and found that there was not much of a difference, and sometimes found it was slower. Once Kodi 18 is fully released and stable I might look into it again.

Yes it is possible to disable caching in urlquick, you can pass a max_age parameter to your request.
* -1 Will disable caching.
* 0 Will enable caching but will send conditional_headers to check if content has changed. pervent re-downloading of content if cache is already up to date.
* 1+ This is the max age in seconds that the cache will stay fresh for.

`urlquick.get("http://example.ie", max_age=-1)`

**Comment by sy6sy2** [comment]
Thank you very munch for your detailed answer and your tests about time!

Now it's time to try your framework in real conditions with our addon ;-)
Hope you will have time to implement the Gettext emulation.

I stay tuned ;-)

**Comment by willforde** [comment]
I already did. It's in the dev branch.

See: [https://scriptmodulecodequick.readthedocs.io/en/latest/api/script.html#codequick.script.Script.localize](https://scriptmodulecodequick.readthedocs.io/en/latest/api/script.html#codequick.script.Script.localize)

**Comment by sy6sy2** [comment]
Awesome!
I will try it tonight!
