### ISSUE TITLE
SetSubtitles in codequick

### ISSUE THREAD

**Issue by wwark** [willforde/script.module.codequick#8]
Hi Willforde,

I work with @SylvainCecchetto. We start to move on the framework codequick.
We have a question: how can we set a subtilte in codequick ? 

Thank you, Best regards,
Wwark.

**Comment by willforde** [comment]
I didn't directly add support for that but you can still do it by accessing the underlining Kodi listitem.
```
item = codequick.Listitem()
item.listitem.setSubtitles(['special://temp/example.srt', 'http://example.com/example.srt'])
```

I hope this answers your question.

**Comment by wwark** [comment]
Thank you.
It answers my question.
BR,
Wwark

**Comment by Forage** [comment]
This makes it a bit odd that the subtitle_language can be set, according to the documentation.
Could we consider this issue as a feature request instead?

**Comment by willforde** [comment]
You can now do the following to add subtitles.
```
item.subtitles.append("http://example.com/example.srt")
```

**Comment by Forage** [comment]
Great, many thanks :)
